<?php
/**
 * ItemSnapshotTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Item Feed Service
 *
 * The Feed API provides the ability to download TSV_GZIP feed files containing eBay items and an hourly snapshot file of the items that have changed within an hour for a specific category, date and marketplace. <p>In addition to the API, there is an open source <a href=\"https://github.com/eBay/FeedSDK\" target=\"_blank\">Feed SDK</a> written in Java that downloads, combines files into a single file when needed, and unzips the entire feed file. It also lets you specify field filters to curate the items in the file.</p>
 *
 * OpenAPI spec version: v1_beta.19.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ItemSnapshotTest Class Doc Comment
 *
 * @category    Class
 * @description The type that defines the columns returned in the Hourly Snapshot feed file. Note: When the value of the availability column is UNAVAILABLE, only the itemId and availability columns are populated.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItemSnapshotTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ItemSnapshot"
     */
    public function testItemSnapshot()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "availability"
     */
    public function testPropertyAvailability()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "image_url"
     */
    public function testPropertyImageUrl()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "buying_options"
     */
    public function testPropertyBuyingOptions()
    {
    }

    /**
     * Test attribute "seller_username"
     */
    public function testPropertySellerUsername()
    {
    }

    /**
     * Test attribute "seller_feedback_percentage"
     */
    public function testPropertySellerFeedbackPercentage()
    {
    }

    /**
     * Test attribute "seller_feedback_score"
     */
    public function testPropertySellerFeedbackScore()
    {
    }

    /**
     * Test attribute "gtin"
     */
    public function testPropertyGtin()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "mpn"
     */
    public function testPropertyMpn()
    {
    }

    /**
     * Test attribute "epid"
     */
    public function testPropertyEpid()
    {
    }

    /**
     * Test attribute "condition_id"
     */
    public function testPropertyConditionId()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "price_value"
     */
    public function testPropertyPriceValue()
    {
    }

    /**
     * Test attribute "price_currency"
     */
    public function testPropertyPriceCurrency()
    {
    }

    /**
     * Test attribute "primary_item_group_id"
     */
    public function testPropertyPrimaryItemGroupId()
    {
    }

    /**
     * Test attribute "primary_item_group_type"
     */
    public function testPropertyPrimaryItemGroupType()
    {
    }

    /**
     * Test attribute "item_end_date"
     */
    public function testPropertyItemEndDate()
    {
    }

    /**
     * Test attribute "seller_item_revision"
     */
    public function testPropertySellerItemRevision()
    {
    }

    /**
     * Test attribute "item_location_country"
     */
    public function testPropertyItemLocationCountry()
    {
    }

    /**
     * Test attribute "localized_aspects"
     */
    public function testPropertyLocalizedAspects()
    {
    }

    /**
     * Test attribute "seller_trust_level"
     */
    public function testPropertySellerTrustLevel()
    {
    }

    /**
     * Test attribute "image_altering_prohibited"
     */
    public function testPropertyImageAlteringProhibited()
    {
    }

    /**
     * Test attribute "estimated_available_quantity"
     */
    public function testPropertyEstimatedAvailableQuantity()
    {
    }

    /**
     * Test attribute "availability_threshold_type"
     */
    public function testPropertyAvailabilityThresholdType()
    {
    }

    /**
     * Test attribute "availability_threshold"
     */
    public function testPropertyAvailabilityThreshold()
    {
    }

    /**
     * Test attribute "item_snapshot_date"
     */
    public function testPropertyItemSnapshotDate()
    {
    }

    /**
     * Test attribute "original_price_value"
     */
    public function testPropertyOriginalPriceValue()
    {
    }

    /**
     * Test attribute "original_price_currency"
     */
    public function testPropertyOriginalPriceCurrency()
    {
    }

    /**
     * Test attribute "discount_amount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "discount_percentage"
     */
    public function testPropertyDiscountPercentage()
    {
    }

    /**
     * Test attribute "returns_accepted"
     */
    public function testPropertyReturnsAccepted()
    {
    }

    /**
     * Test attribute "return_period_value"
     */
    public function testPropertyReturnPeriodValue()
    {
    }

    /**
     * Test attribute "return_period_unit"
     */
    public function testPropertyReturnPeriodUnit()
    {
    }

    /**
     * Test attribute "refund_method"
     */
    public function testPropertyRefundMethod()
    {
    }

    /**
     * Test attribute "return_method"
     */
    public function testPropertyReturnMethod()
    {
    }

    /**
     * Test attribute "return_shipping_cost_payer"
     */
    public function testPropertyReturnShippingCostPayer()
    {
    }

    /**
     * Test attribute "energy_efficiency_class"
     */
    public function testPropertyEnergyEfficiencyClass()
    {
    }

    /**
     * Test attribute "additional_image_urls"
     */
    public function testPropertyAdditionalImageUrls()
    {
    }

    /**
     * Test attribute "delivery_options"
     */
    public function testPropertyDeliveryOptions()
    {
    }

    /**
     * Test attribute "ship_to_included_regions"
     */
    public function testPropertyShipToIncludedRegions()
    {
    }

    /**
     * Test attribute "ship_to_excluded_regions"
     */
    public function testPropertyShipToExcludedRegions()
    {
    }

    /**
     * Test attribute "accepted_payment_methods"
     */
    public function testPropertyAcceptedPaymentMethods()
    {
    }

    /**
     * Test attribute "qualified_programs"
     */
    public function testPropertyQualifiedPrograms()
    {
    }

    /**
     * Test attribute "lot_size"
     */
    public function testPropertyLotSize()
    {
    }

    /**
     * Test attribute "shipping_cost_type"
     */
    public function testPropertyShippingCostType()
    {
    }

    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {
    }

    /**
     * Test attribute "additional_shipping_cost_per_unit"
     */
    public function testPropertyAdditionalShippingCostPerUnit()
    {
    }

    /**
     * Test attribute "quantity_used_for_estimate"
     */
    public function testPropertyQuantityUsedForEstimate()
    {
    }

    /**
     * Test attribute "shipping_carrier_code"
     */
    public function testPropertyShippingCarrierCode()
    {
    }

    /**
     * Test attribute "shipping_service_code"
     */
    public function testPropertyShippingServiceCode()
    {
    }

    /**
     * Test attribute "shipping_type"
     */
    public function testPropertyShippingType()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "unit_pricing_measure"
     */
    public function testPropertyUnitPricingMeasure()
    {
    }

    /**
     * Test attribute "inferred_epid"
     */
    public function testPropertyInferredEpid()
    {
    }

    /**
     * Test attribute "item_creation_date"
     */
    public function testPropertyItemCreationDate()
    {
    }

    /**
     * Test attribute "legacy_item_id"
     */
    public function testPropertyLegacyItemId()
    {
    }

    /**
     * Test attribute "alerts"
     */
    public function testPropertyAlerts()
    {
    }
}
